

-- Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue
from customer_behavior.customer
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer_behavior.customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer_behavior.customer);

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, Round(AVG(review_rating),2) as "Average Product Rating"
from customer_behavior.customer
group by item_purchased
order by AVG(review_rating) desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, 
Round(AVG(purchase_amount),2) as round
from customer_behavior.customer
where shipping_type in ('Standard', 'Express')
group by shipping_type
order by round desc;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue
-- between subscribers and non-subscribers
select subscription_status,
Count(customer_id) as total_customers,
Round(AVG(purchase_amount),2) as avg_spend,
Round(SUM(purchase_amount),2) as total_revenue
from customer_behavior.customer
group by subscription_status
order by total_revenue, avg_spend desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
Round(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*) * 100,2) as discount_rate
from customer_behavior.customer
group by item_purchased
order by discount_rate desc
Limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total
-- number of previous purchases, and show the count of each segment. 
with customer_type as(
select customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases between 2 and 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
from customer_behavior.customer
)

select customer_segment, Count(*) as "Number of Customers"
from customer_type
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 
with item_counts as(
select category,
item_purchased,
Count(customer_id) as total_orders,
Row_Number() Over (partition by category order by count(customer_id) desc) as item_rank
from customer_behavior.customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
Count(customer_id) as repeat_buyers
from customer_behavior.customer
where previous_purchases > 5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group? 
select age_group,
SUM(purchase_amount) as total_revenue
from customer_behavior.customer
group by age_group
order by total_revenue desc;